version: "3.9"

networks:
  ndsnet:
    driver: bridge
    external: true

volumes:
  sys_postgres_data:

services:
  # SOURCE POSTGRES
  source-postgres:
    image: postgres:13
    container_name: source-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - sys_postgres_data:/var/lib/postgresql/data
      - ./initdb/source:/docker-entrypoint-initdb.d  
    networks:
      - ndsnet
    restart: always

  # SPARK MASTER
  spark-master:
    user: "0:0"
    image: bitnami/spark:3.5.0
    container_name: spark-master
    ports:
      - "8082:8080"
      - "7077:7077"
    volumes:
      - ./spark/src:/opt/bitnami/spark/workspace
      - ./etl/bronze:/home/jovyan/work/data/bronze:rw
      - ./etl/silver:/home/jovyan/work/data/silver:rw
      - ./etl/gold:/home/jovyan/work/data/gold:rw
      - ./spark/jars/postgresql-42.7.3.jar:/opt/bitnami/spark/jars/postgresql.jar
      - ./spark/jars/delta-core_2.12-2.4.0.jar:/opt/bitnami/spark/jars/delta-core.jar
      - ./spark/jars/delta-storage-3.2.0.jar:/opt/bitnami/spark/jars/delta-storage.jar
    environment:
      - SPARK_MODE=master
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars/*
      - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
      - SPARK_SQL_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog
    networks:
      - ndsnet

  # SPARK WORKER
  spark-worker:
    user: "0:0"
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./spark/src:/opt/bitnami/spark/workspace
      - ./etl/bronze:/home/jovyan/work/data/bronze:rw
      - ./etl/silver:/home/jovyan/work/data/silver:rw
      - ./etl/gold:/home/jovyan/work/data/gold:rw
      - ./spark/jars/postgresql-42.7.3.jar:/opt/bitnami/spark/jars/postgresql.jar
      - ./spark/jars/delta-core_2.12-2.4.0.jar:/opt/bitnami/spark/jars/delta-core.jar
      - ./spark/jars/delta-storage-3.2.0.jar:/opt/bitnami/spark/jars/delta-storage.jar
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4g         
      - SPARK_DRIVER_MEMORY=4g 
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars/*
      - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
      - SPARK_SQL_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog
      - HADOOP_USER_NAME=jovyan
    networks:
      - ndsnet

  # JUPYTER NOTEBOOK
  jupyter:
    user: "0:0"
    build:
      context: ./jupyter
      dockerfile: ./Dockerfile
    container_name: jupyter
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
      - ./etl/bronze:/home/jovyan/work/data/bronze:rw
      - ./etl/silver:/home/jovyan/work/data/silver:rw
      - ./etl/gold:/home/jovyan/work/data/gold:rw
      - ./spark/jars/postgresql-42.7.3.jar:/usr/local/spark/jars/postgresql.jar
      - ./spark/jars/delta-core_2.12-2.4.0.jar:/usr/local/spark/jars/delta-core.jar
      - ./spark/jars/delta-storage-3.2.0.jar:/usr/local/spark/jars/delta-storage.jar
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYSPARK_PYTHON=python3
      - HADOOP_USER_NAME=jovyan
      - SPARK_SQL_EXTENSIONS=io.delta.sql.DeltaSparkSessionExtension
      - SPARK_SQL_CATALOG=org.apache.spark.sql.delta.catalog.DeltaCatalog
    networks:
      - ndsnet

  # WEB APP (Node.js / JS)
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=source-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - source-postgres
    networks:
      - ndsnet
