apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka:9092"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL
            value: "PLAINTEXT"  # Set security protocol for listeners
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT"  # Security protocol map for Kafka listeners
          - name: KAFKA_CFG_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"  # Zookeeper connection address
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
